company-name:
  target: dev
  outputs:
    dev:
      type: postgres
      host: localhost
      user: root
      password: root
      port: 5432
      dbname: ny_taxi # or database instead of dbname
      schema: new_york_taxi_data
      [keepalives_idle](#keepalives_idle): 0 # default 0, indicating the system default. See below
      connect_timeout: 10 # default 10 seconds
      [retries](#retries): 1  # default 1 retry on error/timeout when opening connections  